DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ds') THEN
        CREATE ROLE ds LOGIN PASSWORD 'ds';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'logs') THEN
        CREATE ROLE logs LOGIN PASSWORD 'logs';
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS ds AUTHORIZATION ds;
CREATE SCHEMA IF NOT EXISTS logs AUTHORIZATION logs;
CREATE SCHEMA IF NOT EXISTS stg;

GRANT USAGE, CREATE ON SCHEMA ds TO postgres;
GRANT USAGE, CREATE ON SCHEMA logs TO postgres;
GRANT USAGE, CREATE ON SCHEMA stg TO postgres;
